# Generated by Django 3.1.7 on 2021-04-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_pill_products_routine'),
    ]

    