# Generated by Django 3.1.7 on 2021-04-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20210408_1447'),
    ]

    