# Generated by Django 3.1.7 on 2021-04-08 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20210408_1532'),
    ]

   
