# Generated by Django 3.1.7 on 2021-04-09 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_auto_20210408_2017'),
    ]

   