# Generated by Django 3.1.7 on 2021-04-09 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_remove_routine_pill'),
    ]

   